version: '3.9'


networks:
  webapp:


services:
    nginx:
      image: nginx:latest
      container_name: ${APP_NAME}_nginx
      ports:
      - "8080:80"
      links:
      - php
      volumes:
      - ./:/var/www/html
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      depends_on:
      - php
      - postgresql
      networks:
      - webapp

  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ${APP_NAME}_php
    ports:
    - "9001:9000"
    volumes:
    - /.:/var/www/html
    networks:
    - gdsc



  postgresql:
      image: postgres:latest
      container_name: ${APP_NAME}_psql
      restart: on-failure
      ports:
      - "5433:5432"
      volumes:
      - ./postgres_data:/var/lib/postgresql
      environment:
        POSTGRES_USER: ${DB_USERNAME}
        POSTGRES_PASSWORD: ${DB_PASSWORD}
        POSTGRES_DB: ${DB_DATABASE}


      networks:
      - webapp




